### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by babluroy** [Zebreus/replicate-api#3] opened 2023-02-21 19:24 UTC
Access to fetch at 'https://api.replicate.com/v1/models/stability-ai/stable-diffusion' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

TypeError: Failed to fetch
    at makeApiRequest (makeApiRequest.js?83b1:17:1)
    at async getModel (getModel.js?af06:15:1)
    at async predict (predict.js?a0c8:20:1)
    at async check (index.js?743a:35:22)

**Comment by zebreus** [comment] 2023-02-21 20:17
I can reproduce the issue. I think it is a replicate issue because they dont send CORS headers but am not sure and will look into this.

Keep in mind that if you use the replicate API clientside, your token also needs to be available clientside, which is probably something you do not want.

**Comment by zebreus** [comment] 2023-02-21 20:56
It seems like the replicate API does not return CORS headers to prevent us from doing stupid things.


You can run a proxy server to the replicate API that allows access from anywhere using cors-backdoor like this:

```console
npx cors-backdoor --target https://api.replicate.com/v1/ --port 3005
```

Then you can pass an apiUrl to the predict function to use the proxy instead of the real URL:

```typescript
  const result = await predict({
    ...
    apiUrl: "http://localhost:3005/",
  })
```

You should probably not do this in production, as this will allow anyone to access the replicate API through your proxy.


The people at [replicate-js](https://github.com/nicholascelestin/replicate-js) use a proxy that adds the headers and adds the token serverside. If that is paired with correct CORS headers that only allow access from your side, it is at least a bit more secure. I think cors-backdoor can also be configured with more restrictive headers.

**Comment by zebreus** [comment] 2023-02-25 12:05
@babluroy I am closing this issue, as this is a problem with the replicate API not with this library.

**Closed as completed by zebreus** 2023-02-25 12:05 UTC
